# Generated by Django 5.2.17 on 2026-09-09 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MegaverseCommerceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("storefront", "Storefront"),
                            ("product", "Product"),
                            ("order", "Order"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier of the resource in MajicMall Megaverse.",
                        max_length=255,
                    ),
                ),
                (
                    "atl_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Optional ATL's Hottest-facing destination slug.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-authoritative presentation/integration metadata only.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Megaverse Commerce Reference",
                "verbose_name_plural": "Megaverse Commerce References",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource_type", "external_ref"),
                        name="unique_megaverse_commerce_reference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MegaverseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "megaverse_user_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable external identifier for this user in MajicMall Megaverse.",
                        max_length=255,
                    ),
                ),
                ("is_linked", models.BooleanField(default=False)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="megaverse_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Megaverse Connection",
                "verbose_name_plural": "Megaverse Connections",
            },
        ),
    ]
