# Generated by Django 5.2.17 on 2026-09-13 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("megaverse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="megaverseconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("megaverse_user_ref", ""), _negated=True),
                fields=("megaverse_user_ref",),
                name="uniq_nonblank_megaverse_user_ref",
            ),
        ),
    ]
