# Generated by Django 5.2.7 on 2026-07-01 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BallotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When voting becomes active. Leave blank to start immediately.",
                        null=True,
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When voting ends. Leave blank for no scheduled end.",
                        null=True,
                    ),
                ),
                (
                    "paused",
                    models.BooleanField(
                        default=False,
                        help_text="Temporarily pause voting without changing dates.",
                    ),
                ),
                (
                    "stopped",
                    models.BooleanField(
                        default=False, help_text="Hard-stop voting immediately."
                    ),
                ),
                (
                    "announcement",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional public message/banner text.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ballot Settings",
                "verbose_name_plural": "Ballot Settings",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("music", "Music"),
                            ("business", "Business"),
                            ("community", "Community"),
                            ("entertainment", "Entertainment"),
                            ("food", "Food"),
                            ("sports", "Sports"),
                            ("beauty", "Beauty"),
                            ("fashion", "Fashion"),
                            ("media", "Media"),
                        ],
                        default="general",
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["group", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="nominees/"),
                ),
                ("photo_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("website", models.URLField(blank=True, default="")),
                ("social_link", models.URLField(blank=True, default="")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "upload_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to="ballot.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="NominationCategoryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomination_requests",
                        to="ballot.category",
                    ),
                ),
                (
                    "source_nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requests",
                        to="ballot.nominee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssociationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association_memberships",
                        to="ballot.nominee",
                    ),
                ),
            ],
            options={
                "ordering": ["nominee__name"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="ballot.category",
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="ballot.nominee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="nominee",
            index=models.Index(
                fields=["category", "is_active"], name="ballot_nomi_categor_593b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nominee",
            index=models.Index(fields=["name"], name="ballot_nomi_name_01ef6f_idx"),
        ),
        migrations.AddConstraint(
            model_name="nominee",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_nominee_name_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="nominationcategoryrequest",
            constraint=models.UniqueConstraint(
                fields=("requester", "source_nominee", "target_category"),
                name="unique_category_request_per_nominee",
            ),
        ),
        migrations.AddConstraint(
            model_name="associationmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "nominee"), name="unique_user_nominee_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["email", "category"], name="ballot_vote_email_959c08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["category", "nominee"], name="ballot_vote_categor_3ae48c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("email", "category"), name="one_vote_per_email_per_category"
            ),
        ),
    ]
