# Generated by Django 5.2.7 on 2026-07-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominee",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                help_text="Only approved nominees appear on the public ballot.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nominee",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
