# Generated by Django 5.2.7 on 2026-07-02 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0002_nominee_approval_status_nominee_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("business_name", models.CharField(blank=True, max_length=180)),
                ("social_media", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("notification_email", models.EmailField(blank=True, max_length=254)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="association_profiles/"
                    ),
                ),
                (
                    "special_interest",
                    models.TextField(
                        blank=True,
                        help_text="Tell us what you are most interested in: entertainment, events, media, business, venues, creative work, sponsorship, community, etc.",
                    ),
                ),
                (
                    "member_level",
                    models.CharField(
                        choices=[
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="silver",
                        max_length=20,
                    ),
                ),
                (
                    "member_since",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__username",),
            },
        ),
    ]
