# Generated by Django 5.2.7 on 2026-08-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0003_associationprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillboardAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser_name", models.CharField(max_length=160)),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("homepage_top", "Homepage Red Carpet Billboard"),
                            ("homepage_video", "Homepage TV Sponsor Billboard"),
                            ("voting_top", "Voting Page Billboard"),
                            ("category_top", "Category Sponsor Billboard"),
                            ("nominee_profile", "Nominee Profile Sponsor"),
                            ("confirmation", "Confirmation Page Billboard"),
                            ("atl_tv", "ATL TV Sponsor Billboard"),
                        ],
                        default="homepage_top",
                        max_length=40,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="billboards/"),
                ),
                ("destination_url", models.URLField(blank=True)),
                (
                    "call_to_action",
                    models.CharField(default="Learn More", max_length=80),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "impressions_note",
                    models.CharField(
                        blank=True,
                        help_text="Optional internal note, such as package name or sponsor slot.",
                        max_length=180,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Billboard Ad",
                "verbose_name_plural": "Billboard Ads",
                "ordering": ["priority", "-created_at"],
            },
        ),
    ]
