# Generated by Django 5.2.7 on 2026-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0004_billboardad"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=180)),
                ("contact_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("website", models.URLField(blank=True)),
                (
                    "placement_interest",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage Billboard"),
                            ("voting", "Voting Page Billboard"),
                            ("category", "Category Sponsor"),
                            ("nominee", "Nominee Profile Sponsor"),
                            ("atl_tv", "ATL TV Sponsor"),
                            ("full_campaign", "Full ATL’s Hottest Campaign"),
                        ],
                        default="homepage",
                        max_length=40,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        help_text="Optional budget range or campaign spend.",
                        max_length=120,
                    ),
                ),
                (
                    "campaign_message",
                    models.TextField(
                        blank=True,
                        help_text="What does the advertiser want to promote?",
                    ),
                ),
                ("is_contacted", models.BooleanField(default=False)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Advertising Inquiry",
                "verbose_name_plural": "Advertising Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
