# Generated by Django 5.2.7 on 2026-08-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0005_advertisinginquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisinginquiry",
            name="creative_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about ad creative, sizing, copy, links, or campaign instructions.",
            ),
        ),
        migrations.AddField(
            model_name="advertisinginquiry",
            name="creative_upload",
            field=models.FileField(
                blank=True,
                help_text="Optional ad creative, flyer, logo, or campaign artwork.",
                null=True,
                upload_to="advertising_inquiries/",
            ),
        ),
        migrations.AddField(
            model_name="advertisinginquiry",
            name="requested_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisinginquiry",
            name="requested_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
