# Generated by Django 5.2.7 on 2026-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0006_advertisinginquiry_creative_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationprofile",
            name="social_media",
            field=models.URLField(blank=True, null=True),
        ),
    ]
