# Generated by Django 5.2.7 on 2026-08-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0008_membershipplan_membershipbenefit_membershipreward_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="ATL's Hottest Awards Campaign", max_length=160
                    ),
                ),
                ("slug", models.SlugField(default="atl-hottest-awards", unique=True)),
                (
                    "nominations_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Allow nominees to be submitted during the nomination period.",
                    ),
                ),
                (
                    "voting_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Manual master switch. Admin can turn voting on/off instantly.",
                    ),
                ),
                (
                    "campaign_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Voting opens on this date/time if voting is enabled.",
                        null=True,
                    ),
                ),
                (
                    "campaign_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Voting closes after this date/time.",
                        null=True,
                    ),
                ),
                (
                    "is_active_campaign",
                    models.BooleanField(
                        default=True,
                        help_text="Only one campaign should normally be active at a time.",
                    ),
                ),
                (
                    "public_message",
                    models.CharField(
                        blank=True,
                        default="Voting is not open yet. Nominations may still be active.",
                        max_length=220,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active_campaign", "-created_at"],
            },
        ),
    ]
