# Generated by Django 5.2.7 on 2026-08-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0009_votingcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominee",
            name="nominator_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Valid Email Address"
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="nominator_name",
            field=models.CharField(
                blank=True,
                max_length=160,
                verbose_name="ATL's Hottest Fan (Name of Person Nominating)",
            ),
        ),
    ]
