# Generated by Django 5.2.7 on 2026-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0010_nominee_nominator_email_nominee_nominator_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtlsHottestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("events", "Events"),
                            ("festivals", "Festivals"),
                            ("nightlife", "Nightlife"),
                            ("special_promotions", "Special Promotions"),
                            ("whats_happening_today", "What's Happening Today"),
                        ],
                        default="events",
                        max_length=40,
                    ),
                ),
                ("organizer_name", models.CharField(max_length=160)),
                ("organizer_email", models.EmailField(max_length=254)),
                ("organizer_phone", models.CharField(blank=True, max_length=40)),
                ("venue_name", models.CharField(blank=True, max_length=180)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(default="Atlanta", max_length=120)),
                ("state", models.CharField(default="GA", max_length=40)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "flyer",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/flyers/"
                    ),
                ),
                ("ticket_link", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("show_today", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ATL's Hottest Event",
                "verbose_name_plural": "ATL's Hottest Events",
                "ordering": ["starts_at", "title"],
            },
        ),
    ]
