# Generated by Django 5.2.7 on 2026-08-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0011_atlshottestevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlshottestevent",
            name="show_on_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
