# Generated by Django 5.2.7 on 2026-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0012_atlshottestevent_show_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlshottestevent",
            name="homepage_amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="atlshottestevent",
            name="homepage_package",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No Homepage Promotion"),
                    ("24_hours", "24 Hours"),
                    ("3_days", "3 Days"),
                    ("7_days", "7 Days"),
                    ("custom", "Custom Campaign"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="atlshottestevent",
            name="homepage_payment_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("unpaid", "Unpaid"),
                    ("pending", "Payment Pending"),
                    ("paid", "Paid"),
                    ("comp", "Complimentary / Admin Comp"),
                    ("refunded", "Refunded"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="atlshottestevent",
            name="homepage_promotion_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atlshottestevent",
            name="homepage_promotion_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="atlshottestevent",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Master switch for premium homepage event promotion.",
            ),
        ),
    ]
