# Generated by Django 5.2.7 on 2026-08-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0013_atlshottestevent_homepage_amount_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPromotionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producer_name", models.CharField(max_length=160)),
                ("producer_email", models.EmailField(max_length=254)),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("24_hours", "24 Hours"),
                            ("3_days", "3 Days"),
                            ("7_days", "7 Days"),
                            ("custom", "Custom Campaign"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_start", models.DateTimeField()),
                ("requested_end", models.DateTimeField(blank=True, null=True)),
                (
                    "quoted_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("paid", "Paid"),
                            ("activated", "Activated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_orders",
                        to="ballot.atlshottestevent",
                    ),
                ),
            ],
        ),
    ]
