# Generated by Django 5.2.7 on 2026-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0014_eventpromotionorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPromotionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("24_hours", "24 Hours"),
                            ("3_days", "3 Days"),
                            ("7_days", "7 Days"),
                            ("custom", "Custom Campaign"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only active packages can be purchased by producers.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_order", "amount"),
            },
        ),
        migrations.AddField(
            model_name="eventpromotionorder",
            name="is_complimentary",
            field=models.BooleanField(
                default=False,
                help_text="Staff-authorized complimentary promotion. Allows activation without a paid dollar amount.",
            ),
        ),
    ]
