# Generated by Django 5.2.7 on 2026-08-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0016_seed_event_promotion_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpromotionorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventpromotionorder",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventpromotionorder",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventpromotionorder",
            name="stripe_payment_status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
