# Generated by Django 5.2.7 on 2026-09-02 06:21

import ballot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0018_eventpromotionorder_public_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisinginquiry",
            name="creative_upload",
            field=models.FileField(
                blank=True,
                help_text="Optional JPG, PNG, or WEBP ad creative, flyer, logo, or campaign artwork. Maximum 10 MB.",
                null=True,
                upload_to="advertising_inquiries/",
                validators=[ballot.models.validate_safe_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="associationprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="association_profiles/",
                validators=[ballot.models.validate_safe_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="atlshottestevent",
            name="flyer",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/flyers/",
                validators=[ballot.models.validate_safe_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="billboardad",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="billboards/",
                validators=[ballot.models.validate_safe_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="nominees/",
                validators=[ballot.models.validate_safe_image_upload],
            ),
        ),
    ]
