# Generated by Django 5.2.17 on 2026-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0019_secure_image_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billboardad",
            name="placement",
            field=models.CharField(
                choices=[
                    ("sitewide", "ATL's Hottest Sitewide Billboard"),
                    ("homepage_top", "Homepage Red Carpet Billboard"),
                    ("homepage_video", "Homepage TV Sponsor Billboard"),
                    ("voting_top", "Voting Page Billboard"),
                    ("category_top", "Category Sponsor Billboard"),
                    ("nominee_profile", "Nominee Profile Sponsor"),
                    ("events_top", "What's Happening In The ATL Billboard"),
                    ("marketplace_top", "ATL's Hottest Marketplace Billboard"),
                    ("membership_top", "Membership Billboard"),
                    ("advertising_top", "Advertising Command Center Billboard"),
                    ("confirmation", "Confirmation Page Billboard"),
                    ("atl_tv", "ATL TV Sponsor Billboard"),
                ],
                default="homepage_top",
                max_length=40,
            ),
        ),
    ]
