# Generated by Django 5.2.17 on 2026-09-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0021_alter_advertisinginquiry_placement_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="billboardad",
            name="allocated_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount of the campaign budget allocated to this billboard property.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billboardad",
            name="campaign_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Advertiser's total campaign budget across all selected properties.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billboardad",
            name="is_premium_property",
            field=models.BooleanField(
                default=False,
                help_text="Marks premium inventory such as major homepage billboard properties.",
            ),
        ),
        migrations.AddField(
            model_name="billboardad",
            name="minimum_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum spend required for this billboard property.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="billboardad",
            name="purchase_type",
            field=models.CharField(
                choices=[
                    ("rotation", "Rotating Billboard Slot"),
                    ("exclusive", "Exclusive Whole Billboard"),
                ],
                default="rotation",
                help_text="Rotating slots share this property. Exclusive purchases take over the whole billboard while active.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="billboardad",
            name="rotation_weight",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Relative rotation frequency. 1 = standard; higher values receive proportionally more appearances.",
            ),
        ),
    ]
