# Generated by Django 5.2.17 on 2026-09-02 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0022_billboardad_allocated_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser_name", models.CharField(max_length=180)),
                ("campaign_name", models.CharField(max_length=180)),
                ("contact_name", models.CharField(blank=True, max_length=140)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget shared across all billboard properties in this campaign.",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_campaign_spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum total spend required for this campaign.",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertising Campaign",
                "verbose_name_plural": "Advertising Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="billboardad",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional campaign that owns the shared budget for this billboard booking.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billboard_ads",
                to="ballot.advertisingcampaign",
            ),
        ),
    ]
