# Generated by Django 5.2.17 on 2026-09-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0023_advertisingcampaign_billboardad_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisinginquiry",
            name="purchase_type",
            field=models.CharField(
                choices=[
                    ("rotation", "Rotating Billboard Slot"),
                    ("exclusive", "Exclusive Whole Billboard"),
                ],
                default="rotation",
                help_text="Choose shared rotating inventory or request the entire billboard exclusively.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="advertisinginquiry",
            name="requested_placements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Advertising property keys requested for this campaign.",
            ),
        ),
        migrations.AddField(
            model_name="advertisinginquiry",
            name="total_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total campaign budget shared across selected advertising properties.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertisinginquiry",
            name="budget_range",
            field=models.CharField(
                blank=True,
                help_text="Optional budget notes or campaign spend details.",
                max_length=120,
            ),
        ),
    ]
