# Generated by Django 5.2.17 on 2026-09-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0024_advertisinginquiry_purchase_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisinginquiry",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisinginquiry",
            name="converted_campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Campaign created from this advertising inquiry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiries",
                to="ballot.advertisingcampaign",
            ),
        ),
    ]
