# Generated by Django 5.2.17 on 2026-09-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0025_advertisinginquiry_converted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillboardAdEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("impression", "Impression"), ("click", "Click")],
                        max_length=20,
                    ),
                ),
                ("placement", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ballot.billboardad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billboard Ad Event",
                "verbose_name_plural": "Billboard Ad Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ad", "event_type", "created_at"],
                        name="ballot_bill_ad_id_6f7a72_idx",
                    )
                ],
            },
        ),
    ]
