# Generated by Django 5.2.17 on 2026-09-05 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0026_billboardadevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominationLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominator_name", models.CharField(max_length=160)),
                ("nominator_email", models.EmailField(max_length=254)),
                (
                    "submitted_nominee_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preserves the nominee name exactly as submitted by the fan.",
                        max_length=160,
                    ),
                ),
                (
                    "communications_consent",
                    models.BooleanField(
                        default=True,
                        help_text="By nominating and/or voting, the participant consented to receiving ATL's Hottest Awards information, updates, announcements, and invitations.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nomination_records",
                        to="ballot.category",
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nomination_records",
                        to="ballot.nominee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["nominee", "category"],
                        name="ballot_nomi_nominee_396a19_idx",
                    ),
                    models.Index(
                        fields=["nominator_email"],
                        name="ballot_nomi_nominat_853c2e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ballot_nomi_created_6e2d98_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nominator_email", "nominee", "category"),
                        name="one_nomination_per_email_nominee_category",
                    )
                ],
            },
        ),
    ]
