# Generated by Django 5.2.17 on 2026-09-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0027_nominationledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfNominationCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person proclaiming I AM ATL's Hottest.",
                        max_length=160,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Valid email address for Check-In and approval communication.",
                        max_length=254,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Website used to help ATL's Hottest review this Check-In.",
                    ),
                ),
                (
                    "social_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Social media address used to help ATL's Hottest review this Check-In.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "communications_consent",
                    models.BooleanField(
                        default=True,
                        help_text="Participant consented to receiving ATL's Hottest Awards information, updates, announcements, and invitations.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("denied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Select from one to five ATL's Hottest categories.",
                        related_name="self_nomination_checkins",
                        to="ballot.category",
                    ),
                ),
                (
                    "created_nominees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Official nominee records created only after this Check-In is approved.",
                        related_name="self_nomination_checkins",
                        to="ballot.nominee",
                    ),
                ),
            ],
            options={
                "verbose_name": "I AM ATL's Hottest Check-In",
                "verbose_name_plural": "I AM ATL's Hottest Check-Ins",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="ballot_self_status_c2436e_idx",
                    ),
                    models.Index(fields=["email"], name="ballot_self_email_07f639_idx"),
                ],
            },
        ),
    ]
