# Generated by Django 5.2.17 on 2026-09-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0028_selfnominationcheckin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.CharField(
                choices=[
                    ("Entertainment", "Entertainment"),
                    ("Events", "Events"),
                    ("Venues", "Venues"),
                    ("Media", "Media"),
                    ("Personalities", "Personalities"),
                    ("Professionals", "Professionals"),
                    ("Community", "Community"),
                ],
                default="Entertainment",
                max_length=40,
            ),
        ),
    ]
