# Generated by Django 5.2.17 on 2026-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0031_populate_category_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.CharField(
                choices=[
                    ("Entertainment", "Entertainment"),
                    ("Events", "Events"),
                    ("Venues", "Venues"),
                    ("Media", "Media"),
                    ("Personalities", "Personalities"),
                    ("Professionals", "Professionals"),
                    ("Fashion & Beauty", "Fashion & Beauty"),
                    ("Community", "Community"),
                    ("Icons / Legends / VIPs", "Icons / Legends / VIPs"),
                ],
                default="Entertainment",
                max_length=40,
            ),
        ),
    ]
