# Generated by Django 5.2.17 on 2026-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0033_expand_award_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominationledger",
            name="communications_consent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When optional promotional communications consent was recorded.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nominationledger",
            name="communications_consent_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version of the communications consent language accepted.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="nominationledger",
            name="communications_consent",
            field=models.BooleanField(
                default=False,
                help_text="Optional consent to receive ATL's Hottest Awards news, announcements, invitations, promotions, and marketing communications.",
            ),
        ),
    ]
