# Generated by Django 5.2.17 on 2026-09-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0035_selfnominationcheckin_communications_consent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisinginquiry",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent meaningful sales/workflow activity for this advertising inquiry.",
                null=True,
            ),
        ),
    ]
