# Generated by Django 5.2.17 on 2026-09-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0036_advertisinginquiry_last_activity_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominationledger",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Awards cycle associated with this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="ballot.votingcampaign",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Awards cycle associated with this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="ballot.votingcampaign",
            ),
        ),
    ]
