# Generated by Django 5.2.17 on 2026-09-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0037_nominationledger_campaign_vote_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominee",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Awards cycle associated with this nominee record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nominees",
                to="ballot.votingcampaign",
            ),
        ),
    ]
