# Generated by Django 5.2.17 on 2026-09-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0038_nominee_campaign"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nominee",
            name="unique_nominee_name_per_category",
        ),
        migrations.AddConstraint(
            model_name="nominee",
            constraint=models.UniqueConstraint(
                fields=("campaign", "name", "category"),
                name="unique_nominee_name_per_campaign_category",
            ),
        ),
    ]
