# Generated by Django 5.2.17 on 2026-09-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0039_remove_nominee_unique_nominee_name_per_category_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nominationledger",
            name="one_nomination_per_email_nominee_category",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="one_vote_per_email_per_category",
        ),
        migrations.AddConstraint(
            model_name="nominationledger",
            constraint=models.UniqueConstraint(
                fields=("campaign", "nominator_email", "nominee", "category"),
                name="one_nomination_per_campaign_email_nominee_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("campaign", "email", "category"),
                name="one_vote_per_email_per_campaign_category",
            ),
        ),
    ]
