# Generated by Django 5.2.17 on 2026-09-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ballot",
            "0040_remove_nominationledger_one_nomination_per_email_nominee_category_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="votingcampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active_campaign", True)),
                fields=("is_active_campaign",),
                name="one_active_voting_campaign",
            ),
        ),
    ]
