# Generated by Django 5.2.17 on 2026-09-23 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0041_votingcampaign_one_active_voting_campaign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("marketing_allowed", models.BooleanField(default=False)),
                (
                    "consented_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When promotional communications were most recently authorized.",
                        null=True,
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Consent-language version associated with the current authorization.",
                        max_length=40,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When promotional communications were most recently withdrawn.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["email"],
            },
        ),
    ]
