# Generated by Django 5.2.17 on 2026-09-25 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0042_communicationpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingDaypart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertising Daypart",
                "verbose_name_plural": "Advertising Dayparts",
                "ordering": ["sort_order", "start_time", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdvertisingPlayoutCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "creative_type",
                    models.CharField(
                        choices=[
                            ("paid", "Paid Advertiser"),
                            ("house", "ATL's Hottest House Promotion"),
                            ("advertise_here", "Advertise Here Fallback"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Creative duration. Must be a multiple of six seconds.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="House/fallback scheduling priority. Higher values receive greater priority.",
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertising Playout Creative",
                "verbose_name_plural": "Advertising Playout Creatives",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdvertisingInventorySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("sitewide", "ATL's Hottest Sitewide Billboard"),
                            ("homepage_top", "Homepage Red Carpet Billboard"),
                            ("homepage_video", "Homepage TV Sponsor Billboard"),
                            ("voting_top", "Voting Page Billboard"),
                            ("category_top", "Category Sponsor Billboard"),
                            ("nominee_profile", "Nominee Profile Sponsor"),
                            ("events_top", "What's Happening In The ATL Billboard"),
                            ("marketplace_top", "ATL's Hottest Marketplace Billboard"),
                            ("membership_top", "Membership Billboard"),
                            ("advertising_top", "Advertising Command Center Billboard"),
                            ("confirmation", "Confirmation Page Billboard"),
                            ("atl_tv", "ATL TV Sponsor Billboard"),
                        ],
                        db_index=True,
                        help_text="Advertising property/display.",
                        max_length=50,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "base_slot_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Base price for one six-second advertising slot.",
                        max_digits=10,
                    ),
                ),
                (
                    "traffic_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Pricing multiplier for NEW inventory. 1.0000 = base rate; 1.2500 = 25% increase.",
                        max_digits=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daypart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_schedules",
                        to="ballot.advertisingdaypart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Inventory Schedule",
                "verbose_name_plural": "Advertising Inventory Schedules",
                "ordering": ["placement", "weekday", "daypart__sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("placement", "weekday", "daypart"),
                        name="unique_ad_inventory_property_day_daypart",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("base_slot_price__gte", 0)),
                        name="ad_inventory_base_price_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("traffic_multiplier__gt", 0)),
                        name="ad_inventory_traffic_multiplier_gt_zero",
                    ),
                ],
            },
        ),
    ]
