# Generated by Django 5.2.17 on 2026-09-25 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0043_advertisingdaypart_advertisingplayoutcreative_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingPlayoutReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appearance_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="All six-second units belonging to one uninterrupted appearance share this identifier.",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("sitewide", "ATL's Hottest Sitewide Billboard"),
                            ("homepage_top", "Homepage Red Carpet Billboard"),
                            ("homepage_video", "Homepage TV Sponsor Billboard"),
                            ("voting_top", "Voting Page Billboard"),
                            ("category_top", "Category Sponsor Billboard"),
                            ("nominee_profile", "Nominee Profile Sponsor"),
                            ("events_top", "What's Happening In The ATL Billboard"),
                            ("marketplace_top", "ATL's Hottest Marketplace Billboard"),
                            ("membership_top", "Membership Billboard"),
                            ("advertising_top", "Advertising Command Center Billboard"),
                            ("confirmation", "Confirmation Page Billboard"),
                            ("atl_tv", "ATL TV Sponsor Billboard"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("paid", "Paid Advertiser"),
                            ("house", "ATL's Hottest House Promotion"),
                            ("advertise_here", "Advertise Here Fallback"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "slot_start",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Start of this exact six-second inventory unit.",
                    ),
                ),
                (
                    "slot_end",
                    models.DateTimeField(
                        help_text="End of this exact six-second inventory unit."
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Position of this slot inside the complete appearance. A 12-second appearance uses sequence numbers 1 and 2.",
                    ),
                ),
                (
                    "appearance_slot_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Total six-second units required by the complete appearance.",
                    ),
                ),
                (
                    "locked_slot_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Sale price permanently locked for this six-second unit. Future rate changes do not alter this value.",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("played", "Played"),
                            ("cancelled", "Cancelled"),
                            ("missed", "Missed"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=20,
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual proof-of-play timestamp.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playout_reservations",
                        to="ballot.advertisingplayoutcreative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Playout Reservation",
                "verbose_name_plural": "Advertising Playout Reservations",
                "ordering": ["placement", "slot_start", "sequence_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("placement", "slot_start"),
                        name="unique_ad_playout_property_slot",
                    ),
                    models.UniqueConstraint(
                        fields=("appearance_id", "sequence_number"),
                        name="unique_ad_playout_appearance_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("locked_slot_price__gte", 0)),
                        name="ad_playout_locked_price_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence_number__gte", 1)),
                        name="ad_playout_sequence_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("appearance_slot_count__gte", 1)),
                        name="ad_playout_slot_count_gte_one",
                    ),
                ],
            },
        ),
    ]
