# Generated by Django 5.2.17 on 2026-09-25 07:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0044_advertisingplayoutreservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingRevenuePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="ATL's Hottest Standard Advertising Revenue Policy",
                        max_length=120,
                    ),
                ),
                (
                    "platform_share_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("15.000"),
                        help_text="ATL's Hottest internal share of advertising media spend. 15.000 means 15 percent.",
                        max_digits=6,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "effective_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertising Revenue Policy",
                "verbose_name_plural": "Advertising Revenue Policies",
                "ordering": ["-effective_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="advertisingplayoutreservation",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Paid advertising campaign that purchased this six-second inventory unit. House and Advertise Here inventory may be blank.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playout_reservations",
                to="ballot.advertisingcampaign",
            ),
        ),
        migrations.CreateModel(
            name="AdvertisingCampaignSpend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appearance_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Appearance identifier shared by all six-second reservation rows represented by this spend entry.",
                        unique=True,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("sitewide", "ATL's Hottest Sitewide Billboard"),
                            ("homepage_top", "Homepage Red Carpet Billboard"),
                            ("homepage_video", "Homepage TV Sponsor Billboard"),
                            ("voting_top", "Voting Page Billboard"),
                            ("category_top", "Category Sponsor Billboard"),
                            ("nominee_profile", "Nominee Profile Sponsor"),
                            ("events_top", "What's Happening In The ATL Billboard"),
                            ("marketplace_top", "ATL's Hottest Marketplace Billboard"),
                            ("membership_top", "Membership Billboard"),
                            ("advertising_top", "Advertising Command Center Billboard"),
                            ("confirmation", "Confirmation Page Billboard"),
                            ("atl_tv", "ATL TV Sponsor Billboard"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "slot_count",
                    models.PositiveIntegerField(
                        help_text="Number of six-second units purchased."
                    ),
                ),
                (
                    "locked_slot_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Locked sale price of one six-second unit at purchase time.",
                        max_digits=10,
                    ),
                ),
                (
                    "media_spend",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total advertiser media value consumed by this appearance.",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_share_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("15.000"),
                        help_text="Revenue-share percentage permanently locked when purchased.",
                        max_digits=6,
                    ),
                ),
                (
                    "platform_share_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="ATL's Hottest internal revenue allocation from media spend.",
                        max_digits=12,
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playout_spend_entries",
                        to="ballot.advertisingcampaign",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_spend_entries",
                        to="ballot.advertisingplayoutcreative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Campaign Spend",
                "verbose_name_plural": "Advertising Campaign Spend",
                "ordering": ["-purchased_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slot_count__gte", 1)),
                        name="ad_campaign_spend_slot_count_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("locked_slot_price__gte", 0)),
                        name="ad_campaign_spend_slot_price_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("media_spend__gte", 0)),
                        name="ad_campaign_spend_media_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("platform_share_percent__gte", 0)),
                        name="ad_campaign_spend_share_percent_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("platform_share_percent__lte", 100)),
                        name="ad_campaign_spend_share_percent_lte_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("platform_share_amount__gte", 0)),
                        name="ad_campaign_spend_share_amount_gte_zero",
                    ),
                ],
            },
        ),
    ]
