# Generated by Django 5.2.17 on 2026-09-27 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0045_advertisingrevenuepolicy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingCampaignCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only active assignments may be selected by automated campaign execution.",
                    ),
                ),
                (
                    "rotation_weight",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Relative campaign-specific delivery weight. Higher values may receive proportionally more appearances.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=100,
                        help_text="Campaign-specific creative priority. Lower values are considered first when priorities differ.",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Time this creative was authorized for campaign delivery.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_assignments",
                        to="ballot.advertisingcampaign",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_assignments",
                        to="ballot.advertisingplayoutcreative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Campaign Creative",
                "verbose_name_plural": "Advertising Campaign Creatives",
                "ordering": ["priority", "-rotation_weight", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "creative"),
                        name="unique_ad_campaign_creative_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rotation_weight__gte", 1)),
                        name="ad_campaign_creative_rotation_weight_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("priority__gte", 1)),
                        name="ad_campaign_creative_priority_gte_one",
                    ),
                ],
            },
        ),
    ]
