# Generated by Django 5.2.17 on 2026-09-27 05:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0046_advertisingcampaigncreative"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingShoppingRunnerLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="autonomous_advertising_shopper",
                        editable=False,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "owner_token",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Unique token identifying the execution currently holding the autonomous shopping lease.",
                        null=True,
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertising Shopping Runner Lock",
                "verbose_name_plural": "Advertising Shopping Runner Lock",
            },
        ),
        migrations.CreateModel(
            name="AdvertisingShoppingExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("locked_out", "Locked Out"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Lease expiration assigned when this execution acquired the autonomous shopping runner lock.",
                        null=True,
                    ),
                ),
                ("lookahead_minutes", models.PositiveIntegerField(default=60)),
                ("campaign_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("purchased_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "failure_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("failure_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertising Shopping Execution",
                "verbose_name_plural": "Advertising Shopping Executions",
                "ordering": ["-started_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lookahead_minutes__gte", 1)),
                        name="ad_shop_execution_lookahead_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("campaign_limit__isnull", True),
                            ("campaign_limit__gte", 1),
                            _connector="OR",
                        ),
                        name="ad_shop_execution_campaign_limit_valid",
                    ),
                ],
            },
        ),
    ]
