# Generated by Django 5.2.17 on 2026-09-29 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0047_advertisingshoppingrunnerlock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisingplayoutcreative",
            name="billboard_ad",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional billboard presentation rendered when this playout creative is delivered.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playout_creatives",
                to="ballot.billboardad",
            ),
        ),
    ]
