# Generated by Django 5.2.17 on 2026-09-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0048_advertisingplayoutcreative_billboard_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisingcampaign",
            name="advertiser_report_token",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
