# Generated by Django 5.2.17 on 2026-09-30 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0050_backfill_advertiser_report_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingcampaign",
            name="advertiser_report_token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
