# Generated by Django 5.2.17 on 2026-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0051_alter_advertisingcampaign_advertiser_report_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisingcampaign",
            name="advertiser_report_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether the secure advertiser delivery report is currently accessible.",
            ),
        ),
    ]
