# Generated by Django 5.2.17 on 2026-10-06 02:08

import ballot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballot", "0052_advertisingcampaign_advertiser_report_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfnominationcheckin",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional phone number for Check-In review or follow-up.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="selfnominationcheckin",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo or image submitted with this Check-In.",
                null=True,
                upload_to="checkins/",
                validators=[ballot.models.validate_safe_image_upload],
            ),
        ),
    ]
